{% set old_query %}
select
    transactiondate,
    businessid,
    businessname,
    partnername,
    relationship,
    crmid,
    pricingplan,
    settlementtype,
    mid,
    mcc,
    firsttransactiondate,
    merchantcountrycode,
    merchantcountry,
    cardissuecountrycode,
    cardissuecountry,
    transactionclass,
    transactioncurrency,
    regionality,
    scheme,
    product,
    cardproduct,
    transactioncount,
    round(totalturnover) as totalturnover,
    round(totalrevenue) as totalrevenue,
    round(msc) as msc,
    round(authfees) as authfees,
    round(declinefees) as declinefees,
    round(chargebackrevenue) as chargebackrevenue,
    round(hrwrevenue) as hrwrevenue,
    round(refundrevenue) as refundrevenue,
    round(creditrevenue) as creditrevenue,
    round(copyrevenue) as copyrevenue,
    round(interchange) as interchange,
    round(schemefeessale) as schemefeessale,
    round(schemefeesnonsale) as schemefeesnonsale,
    round(customergp) as customergp,
    round(customergppercent) as customergppercent,
    round(cashlowsgppercent) as cashlowsgppercent,
    round(totalturnovergbp) as totalturnovergbp,
    round(totalrevenuegbp) as totalrevenuegbp,
    round(mscgbp) as mscgbp,
    round(authfeesgbp) as authfeesgbp,
    round(declinefeesgbp) as declinefeesgbp,
    round(chargebackrevenuegbp) as chargebackrevenuegbp,
    round(hrwrevenuegbp) as hrwrevenuegbp,
    round(refundrevenuegbp) as refundrevenuegbp,
    round(creditrevenuegbp) as creditrevenuegbp,
    round(copyrevenuegbp) as copyrevenuegbp,
    round(interchangegbp) as interchangegbp,
    round(schemefeessalegbp) as schemefeessalegbp,
    round(schemefeesnonsalegbp) as schemefeesnonsalegbp,
    round(customergpgbp) as customergpgbp,
    round(esauthamountgbp) as esauthamountgbp,
    round(estotalincomegbp) as estotalincomegbp,
    round(esincomewithoutmarkupgbp) as esincomewithoutmarkupgbp,
    round(esmarkupamountgbp) as esmarkupamountgbp,
    channel,
    salesperson,
    credit_debit,
    consumer_commercial,
    legal_entity
from
    {{ ref('stg_mssql__analytics_dbo_tblfinancialreport') }}
where
    transactiondate = {{ previous_period_start_date() }}
{% endset %}

{% set new_query %}
select
    transactiondate,
    businessid,
    businessname,
    partnername,
    relationship,
    crmid,
    pricingplan,
    settlementtype,
    mid,
    mcc,
    firsttransactiondate,
    merchantcountrycode,
    merchantcountry,
    cardissuecountrycode,
    cardissuecountry,
    transactionclass,
    transactioncurrency,
    regionality,
    scheme,
    product,
    cardproduct,
    transactioncount,
    round(totalturnover) as totalturnover,
    round(totalrevenue) as totalrevenue,
    round(msc) as msc,
    round(authfees) as authfees,
    round(declinefees) as declinefees,
    round(chargebackrevenue) as chargebackrevenue,
    round(hrwrevenue) as hrwrevenue,
    round(refundrevenue) as refundrevenue,
    round(creditrevenue) as creditrevenue,
    round(copyrevenue) as copyrevenue,
    round(interchange) as interchange,
    round(schemefeessale) as schemefeessale,
    round(schemefeesnonsale) as schemefeesnonsale,
    round(customergp) as customergp,
    round(customergppercent) as customergppercent,
    round(cashlowsgppercent) as cashlowsgppercent,
    round(totalturnovergbp) as totalturnovergbp,
    round(totalrevenuegbp) as totalrevenuegbp,
    round(mscgbp) as mscgbp,
    round(authfeesgbp) as authfeesgbp,
    round(declinefeesgbp) as declinefeesgbp,
    round(chargebackrevenuegbp) as chargebackrevenuegbp,
    round(hrwrevenuegbp) as hrwrevenuegbp,
    round(refundrevenuegbp) as refundrevenuegbp,
    round(creditrevenuegbp) as creditrevenuegbp,
    round(copyrevenuegbp) as copyrevenuegbp,
    round(interchangegbp) as interchangegbp,
    round(schemefeessalegbp) as schemefeessalegbp,
    round(schemefeesnonsalegbp) as schemefeesnonsalegbp,
    round(customergpgbp) as customergpgbp,
    round(esauthamountgbp) as esauthamountgbp,
    round(estotalincomegbp) as estotalincomegbp,
    round(esincomewithoutmarkupgbp) as esincomewithoutmarkupgbp,
    round(esmarkupamountgbp) as esmarkupamountgbp,
    channel,
    salesperson,
    credit_debit,
    consumer_commercial,
    legal_entity
from
    {{ ref('mart_financial_report_records') }}
where
    transactiondate = {{ previous_period_start_date() }}
{% endset %}

{{ audit_helper.compare_queries(
    a_query=old_query,
    b_query=new_query,
    primary_key='transactiondate || businessid || businessname || partnername || channel || crmid || pricingplan || settlementtype || mid || mcc || firsttransactiondate || merchantcountrycode || merchantcountry || cardissuecountrycode || cardissuecountry || transactionclass || transactioncurrency || regionality || scheme || product || cardproduct || salesperson || credit_debit || consumer_commercial ||legal_entity || transactioncount || totalturnover',
    summarize=False
) }}
