parameters:
  - name: TargetPool
    type: string
    default: test.yaml
    values:
      - test.yaml
      - inta.yaml
      - live.yaml
      
trigger: none

pr: none

variables:
- template: ../parameters/pipeline/${{parameters.TargetPool}}

stages:
  #Get Ops team to approve the run
  # - stage: OpsApprove
  #   displayName: Ops to approve the CustomerDemo deployment
  #   jobs:
  #     - deployment: Approve_DemoDeployment
  #       displayName:  Ops to approve the CustomerDemo deployment
  #       continueOnError: false
  #       environment: 'ApprovalGate - Ops'
  #       pool: $(agent_pool)
  #       timeoutInMinutes: 120

  - stage: DeployCode
    displayName: Deploy to CustomerDemo
    # dependsOn: OpsApprove
    # condition: succeeded('OpsApprove')
    jobs:
      - deployment: DeployCode
        environment: $(targetAdoEnvironment)
        displayName: Deploy to CustomerDemo
        pool: $(agent_pool)
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self

              #Copy files to the Customer Demo webserver
              - task: CopyFilesOverSSH@0
                inputs:
                  sshEndpoint: 'TEST-Airflow-01 - SSH - azuredevops'
                  sourceFolder: '$(System.DefaultWorkingDirectory)/code/'
                  contents: |
                    **
                  targetFolder: '/tmp/code/'
                  cleanTargetFolder: true
                  cleanHiddenFilesInTarget: true
                  readyTimeout: '20000'
                  failOnEmptySource: true

              - task: SSH@0
                inputs:
                  sshEndpoint: 'TEST-Airflow-01 - SSH - azuredevops'
                  runOptions: 'inline'
                  inline: |
                    #Very basic sanity check
                    [ -f /tmp/code/Hello ] || exit 1
                    sudo mv /tmp/code /tmp/code-2
                  readyTimeout: '20000'