-- analytics.dbo.tbldatalake in SQL Server is generated by daily run of stored procedure.
-- Here we make sure it has been run according to schedule.
with count_by_date as (
    select
        cast(postingtime as date) as date,
        count(*) as count
    from {{ ref('stg_mssql__analytics_dbo_tbldatalake') }}
    group by cast(postingtime as date)
),

last_14_days as (
    select cast ((current_date + interval '-1 days') as date)
    union distinct
    select cast ((current_date + interval '-2 days') as date)
    union distinct
    select cast ((current_date + interval '-3 days') as date)
    union distinct
    select cast ((current_date + interval '-4 days') as date)
    union distinct
    select cast ((current_date + interval '-5 days') as date)
    union distinct
    select cast ((current_date + interval '-6 days') as date)
    union distinct
    select cast ((current_date + interval '-7 days') as date)
),

joined as (
    select
        last_14_days.date,
        coalesce(count_by_date.count, 0) as count
    from last_14_days
    left join count_by_date on last_14_days.date = count_by_date.date
    order by date
),

issued as (select * from joined where count = 0)

select * from issued
